// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Test.DataModels;

#nullable disable

namespace Test.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20260606054307_Initial migrate")]
    partial class Initialmigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Test.DataModels.Application", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApplicantFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ApplicationStatusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("HandlerComment")
                        .HasColumnType("text");

                    b.Property<string>("Subdivision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TypeEquipmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationStatusId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Subdivision");

                    b.HasIndex("TypeEquipmentId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Test.DataModels.ApplicationStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "New"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "InProgress"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("Test.DataModels.TypeEquipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TypeEquipments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsActive = true,
                            Name = "Ноутбук"
                        },
                        new
                        {
                            Id = 2L,
                            IsActive = true,
                            Name = "Монитор"
                        },
                        new
                        {
                            Id = 3L,
                            IsActive = true,
                            Name = "Принтер"
                        },
                        new
                        {
                            Id = 4L,
                            IsActive = true,
                            Name = "Клавиатура"
                        },
                        new
                        {
                            Id = 5L,
                            IsActive = true,
                            Name = "Мышь"
                        });
                });

            modelBuilder.Entity("Test.DataModels.Application", b =>
                {
                    b.HasOne("Test.DataModels.ApplicationStatus", "ApplicationStatus")
                        .WithMany()
                        .HasForeignKey("ApplicationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.DataModels.TypeEquipment", "TypeEquipment")
                        .WithMany()
                        .HasForeignKey("TypeEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationStatus");

                    b.Navigation("TypeEquipment");
                });
#pragma warning restore 612, 618
        }
    }
}
